Document: nightcap
Title: Debian nightcap Manual
Author: <insert document author here>
Abstract: This manual describes what nightcap is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nightcap/nightcap.sgml.gz

Format: postscript
Files: /usr/share/doc/nightcap/nightcap.ps.gz

Format: text
Files: /usr/share/doc/nightcap/nightcap.text.gz

Format: HTML
Index: /usr/share/doc/nightcap/html/index.html
Files: /usr/share/doc/nightcap/html/*.html
